#!/bin/bash
BLACK='\e[0;30m'
BLUE='\e[0;34m'
GREEN='\e[0;32m'
CYAN='\e[0;36m'
RED='\e[0;31m'
PURPLE='\e[0;35m'
BROWN='\e[0;33m'
LIGHTGRAY='\e[0;37m'
DARKGRAY='\e[1;30m'
LIGHTBLUE='\e[1;34m'
LIGHTGREEN='\e[1;32m'
LIGHTCYAN='\e[1;36m'
LIGHTRED='\e[1;31m'
LIGHTPURPLE='\e[1;35m'
YELLOW='\e[1;33m'
WHITE='\e[1;37m'
NC='\e[0m'              # No Color
clear
		
echo -e "${LIGHTBLUE}Press Enter To Start The Update Of Your Server!"
read enter
sudo apt-get update -y

clear

echo -e "${LIGHTBLUE}Press Enter To Start Installing Perl On Your Server!"
read enter
sudo apt-get install perl -y

clear

echo -e "${LIGHTBLUE}Press Enter To Start Installing Python On Your Server!"
read enter
sudo apt-get install python -y
sudo apt-get install python2 -y
sudo apt-get install python3.4 -y
sudo apt-get install python3-pip -y

clear

echo -e "${LIGHTBLUE}Press Enter To Start DSTAT Installer !"
read enter
sudo apt-get install dstat -y 

clear

echo -e "${LIGHTBLUE}Press Enter To Start GCC Installer !"
read enter
sudo apt-get install build-essential -y
sudo apt-get install manpages-dev -y

clear

echo -e "${LIGHTBLUE}Press Enter To Start Time::HiRes Installer !"
read enter
cpan force install Time::HiRes

clear


echo -e "${LIGHTBLUE}Press Enter To Start Net::RawIP Installer !"
read enter
cpan force install Net::RawIP

clear

echo -e "${LIGHTBLUE}Finish ! You Can Exit (Press Enter)"
read enter
chmod 777 *